# Generated by Django 4.2.4 on 2023-08-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_category_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
