# Generated by Django 4.2.4 on 2023-08-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply', '0004_ordinefornitore_vociordinefornitore'),
        ('cousine', '0006_recipe_recipeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cousine.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityInGrOrMl', models.FloatField()),
                ('scarto', models.FloatField()),
                ('caloPonderale', models.FloatField()),
                ('costoAlGr', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.article')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preparations.preparation')),
            ],
        ),
    ]
