# Generated by Django 4.2.4 on 2023-09-09 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cousine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unitaArrivo', models.IntegerField()),
                ('giacenza_in_gr', models.FloatField()),
                ('prezzo_unita_arrivo', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cousine.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=80)),
                ('citta', models.CharField(max_length=50)),
                ('prov', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20)),
                ('dataPrevista', models.DateField()),
                ('dataConsegna', models.DateField()),
                ('altreRichieste', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VociOrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('note', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.article')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ordinefornitore')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contatto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatto', to='supply.contatto')),
                ('indirizzo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo', to='supply.indirizzo')),
            ],
        ),
        migrations.AddField(
            model_name='ordinefornitore',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=50)),
                ('invoicedate', models.DateField()),
                ('totfood', models.FloatField()),
                ('totnonfood', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier'),
        ),
        migrations.CreateModel(
            name='ArrivoFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingdate', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('conforme', models.BooleanField(default=True)),
                ('scadenza', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.article')),
            ],
        ),
    ]
