# Generated by Django 4.2.4 on 2023-08-23 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=80)),
                ('citta', models.CharField(max_length=50)),
                ('prov', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=50)),
                ('invoicedate', models.DateField()),
                ('totfood', models.FloatField()),
                ('totnonfood', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivoFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomingdate', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('conforme', models.BooleanField(default=True)),
                ('scadenza', models.DateField(default=datetime.datetime.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.article')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='contatto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatto', to='supply.contatto'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='indirizzo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo', to='supply.indirizzo'),
        ),
    ]
