# Generated by Django 4.2.4 on 2023-08-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_contatto_indirizzo_invoice_incoming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivofood',
            name='scadenza',
            field=models.DateField(),
        ),
    ]
