# Generated by Django 4.2.4 on 2023-08-24 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_alter_arrivofood_scadenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20)),
                ('dataPrevista', models.DateField()),
                ('dataConsegna', models.DateField()),
                ('altreRichieste', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='VociOrdineFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('note', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.article')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply.ordinefornitore')),
            ],
        ),
    ]
