# Generated by Django 4.2.4 on 2023-09-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_ordinefornitore_vociordinefornitore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='giacenza',
            new_name='giacenza_in_gr',
        ),
    ]
