# Generated by Django 4.2.4 on 2023-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_rename_giacenza_article_giacenza_in_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prezzo_al_gr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
