# Generated by Django 4.2.4 on 2023-09-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_article_prezzo_al_gr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='prezzo_al_gr',
            new_name='prezzo_al_kg',
        ),
    ]
