# Generated by Django 4.2.4 on 2023-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('A', 'Antipasti'), ('P', 'Primi'), ('S', 'Secondi'), ('D', 'Dessert')], max_length=1)),
            ],
        ),
    ]
