# Generated by Django 4.2.4 on 2023-08-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cousine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fat', models.FloatField()),
                ('starch', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutritional',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nutritionals', to='cousine.nutritionals'),
            preserve_default=False,
        ),
    ]
