# Generated by Django 4.2.4 on 2023-08-24 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cousine', '0002_nutritionals_ingredient_nutritional'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineCucina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
