# Generated by Django 4.2.4 on 2023-08-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cousine', '0003_ordinecucina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='nutritional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cousine.nutritionals'),
        ),
    ]
