# Generated by Django 4.2.4 on 2023-08-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
        ('cousine', '0004_alter_ingredient_nutritional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinecucina',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordinecucina',
            name='richiedente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='ordinecucina',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VociOrdineCucina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('note', models.TextField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cousine.ingredient')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cousine.ordinecucina')),
            ],
        ),
    ]
